behaviors:

  emergency:
    priority: 100
    request: false
    interrupt:
      - 80
      - 50


  task:
    priority: 80
    request: false
    pause:
      - 50
    behavior_path: ../config/trees/task.xml


  task_cloud:
    priority: 50
    request: true

